


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."custom_access_token_hook"("event" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" STABLE
    AS $$
declare
  claims jsonb;
  user_role text;
begin
  select raw_app_meta_data->>'role' into user_role
  from auth.users
  where id = (event->>'user_id')::uuid;

  claims := event->'claims';
  claims := jsonb_set(claims, '{role}', to_jsonb(coalesce(user_role, 'cashier')));
  event := jsonb_set(event, '{claims}', claims);
  
  return event;
end;
$$;


ALTER FUNCTION "public"."custom_access_token_hook"("event" "jsonb") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ACCOUNTS" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "total_present" smallint,
    "earliest-attainment" timestamp with time zone,
    "failed_attempts" smallint,
    "locked_until" timestamp with time zone,
    "device_id" "uuid",
    "auth_user_id" "uuid" NOT NULL,
    "email" "text" NOT NULL
);


ALTER TABLE "public"."ACCOUNTS" OWNER TO "postgres";


ALTER TABLE "public"."ACCOUNTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ACCOUNTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."INVENTORY_RECONCILIATION" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "small_cups" smallint NOT NULL,
    "medium_cups" smallint NOT NULL,
    "large_cups" smallint NOT NULL,
    "opening_cash" smallint NOT NULL,
    "opening_potatoes" smallint NOT NULL,
    "appeal" "jsonb",
    "added_cups" "jsonb",
    "added_potatoes" "jsonb",
    "stores_id" integer NOT NULL
);


ALTER TABLE "public"."INVENTORY_RECONCILIATION" OWNER TO "postgres";


ALTER TABLE "public"."INVENTORY_RECONCILIATION" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."INVENTORY_RECONCILIATION_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."NO_WORKING_DAYS" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "branch" "text" NOT NULL,
    "day" timestamp with time zone NOT NULL,
    "reason" "text"
);


ALTER TABLE "public"."NO_WORKING_DAYS" OWNER TO "postgres";


ALTER TABLE "public"."NO_WORKING_DAYS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."NO_WORKING_DAYS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."PRICE" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "small" smallint NOT NULL,
    "medium" smallint NOT NULL,
    "large" smallint NOT NULL
);


ALTER TABLE "public"."PRICE" OWNER TO "postgres";


ALTER TABLE "public"."PRICE" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PRICING_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."SALES" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "flavor" "text" NOT NULL,
    "size" "text" NOT NULL,
    "online_payment" "text" NOT NULL,
    "stores_id" integer NOT NULL
);


ALTER TABLE "public"."SALES" OWNER TO "postgres";


ALTER TABLE "public"."SALES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."SALES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."STORES" (
    "id" integer NOT NULL,
    "time_in" timestamp with time zone DEFAULT "now"() NOT NULL,
    "username" "text" NOT NULL,
    "ipv4" "text" NOT NULL,
    "branch" "text" NOT NULL,
    "session_id" "uuid" NOT NULL,
    "session_expiration" timestamp with time zone NOT NULL,
    "time_out" timestamp with time zone
);


ALTER TABLE "public"."STORES" OWNER TO "postgres";


ALTER TABLE "public"."STORES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."STORES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."STORE_DEFAULT" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "branch" "text" NOT NULL,
    "small_cups" smallint NOT NULL,
    "medium_cups" smallint NOT NULL,
    "large_cups" smallint NOT NULL,
    "opening_cash" smallint NOT NULL,
    "opening_potatoes" smallint NOT NULL
);


ALTER TABLE "public"."STORE_DEFAULT" OWNER TO "postgres";


ALTER TABLE "public"."STORE_DEFAULT" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."STORE_DEFAULT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."ACCOUNTS"
    ADD CONSTRAINT "ACCOUNTS_auth_email_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."ACCOUNTS"
    ADD CONSTRAINT "ACCOUNTS_auth_email_key1" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."ACCOUNTS"
    ADD CONSTRAINT "ACCOUNTS_auth_email_key2" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."ACCOUNTS"
    ADD CONSTRAINT "ACCOUNTS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."INVENTORY_RECONCILIATION"
    ADD CONSTRAINT "INVENTORY_RECONCILIATION_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."NO_WORKING_DAYS"
    ADD CONSTRAINT "NO_WORKING_DAYS_day_key" UNIQUE ("day");



ALTER TABLE ONLY "public"."NO_WORKING_DAYS"
    ADD CONSTRAINT "NO_WORKING_DAYS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PRICE"
    ADD CONSTRAINT "PRICING_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."SALES"
    ADD CONSTRAINT "SALES_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."STORES"
    ADD CONSTRAINT "STORES_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."STORES"
    ADD CONSTRAINT "STORES_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."STORE_DEFAULT"
    ADD CONSTRAINT "STORE_DEFAULT_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "unique_username_per_day" ON "public"."STORES" USING "btree" ("username", ((("time_in" AT TIME ZONE 'Asia/Manila'::"text"))::"date"));



ALTER TABLE ONLY "public"."ACCOUNTS"
    ADD CONSTRAINT "ACCOUNTS_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."INVENTORY_RECONCILIATION"
    ADD CONSTRAINT "INVENTORY_RECONCILIATION_stores_id_fkey" FOREIGN KEY ("stores_id") REFERENCES "public"."STORES"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."SALES"
    ADD CONSTRAINT "SALES_stores_id_fkey" FOREIGN KEY ("stores_id") REFERENCES "public"."STORES"("id") ON DELETE CASCADE;



ALTER TABLE "public"."ACCOUNTS" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."INVENTORY_RECONCILIATION" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."NO_WORKING_DAYS" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."PRICE" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."SALES" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."STORES" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."STORE_DEFAULT" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT USAGE ON SCHEMA "public" TO "supabase_auth_admin";






















































































































































REVOKE ALL ON FUNCTION "public"."custom_access_token_hook"("event" "jsonb") FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."custom_access_token_hook"("event" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."custom_access_token_hook"("event" "jsonb") TO "supabase_auth_admin";


















GRANT ALL ON TABLE "public"."ACCOUNTS" TO "anon";
GRANT ALL ON TABLE "public"."ACCOUNTS" TO "authenticated";
GRANT ALL ON TABLE "public"."ACCOUNTS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ACCOUNTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ACCOUNTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ACCOUNTS_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."INVENTORY_RECONCILIATION" TO "anon";
GRANT ALL ON TABLE "public"."INVENTORY_RECONCILIATION" TO "authenticated";
GRANT ALL ON TABLE "public"."INVENTORY_RECONCILIATION" TO "service_role";



GRANT ALL ON SEQUENCE "public"."INVENTORY_RECONCILIATION_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."INVENTORY_RECONCILIATION_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."INVENTORY_RECONCILIATION_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."NO_WORKING_DAYS" TO "anon";
GRANT ALL ON TABLE "public"."NO_WORKING_DAYS" TO "authenticated";
GRANT ALL ON TABLE "public"."NO_WORKING_DAYS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."NO_WORKING_DAYS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."NO_WORKING_DAYS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."NO_WORKING_DAYS_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."PRICE" TO "anon";
GRANT ALL ON TABLE "public"."PRICE" TO "authenticated";
GRANT ALL ON TABLE "public"."PRICE" TO "service_role";



GRANT ALL ON SEQUENCE "public"."PRICING_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PRICING_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PRICING_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."SALES" TO "anon";
GRANT ALL ON TABLE "public"."SALES" TO "authenticated";
GRANT ALL ON TABLE "public"."SALES" TO "service_role";



GRANT ALL ON SEQUENCE "public"."SALES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."SALES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."SALES_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."STORES" TO "anon";
GRANT ALL ON TABLE "public"."STORES" TO "authenticated";
GRANT ALL ON TABLE "public"."STORES" TO "service_role";



GRANT ALL ON SEQUENCE "public"."STORES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."STORES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."STORES_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."STORE_DEFAULT" TO "anon";
GRANT ALL ON TABLE "public"."STORE_DEFAULT" TO "authenticated";
GRANT ALL ON TABLE "public"."STORE_DEFAULT" TO "service_role";



GRANT ALL ON SEQUENCE "public"."STORE_DEFAULT_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."STORE_DEFAULT_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."STORE_DEFAULT_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































